[profile.default]
src = 'src'
out = 'artifacts'
libs = ['node_modules']
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@solvprotocol/=node_modules/@solvprotocol/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'forge-std/=node_modules/forge-std/',
    'hardhat/=node_modules/hardhat/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config